baseurl: "/BlogSth"
exclude: ['README.md']
excerpt_separator: "<!--excerpt-->"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

highlighter: rouge
permalink: /posts/:title.html
repository: sjiaming/BlogSth

plugins:
  - jemoji
